FROM python:3.9

# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory to /app
WORKDIR /app

# Copy your application files into the container
COPY app.py .

# Install any necessary dependencies
# Install any needed packages specified in requirements.txt
RUN pip install Flask


# Expose the port your Flask application will run on
EXPOSE 5000

# Define the command to run your Flask application
CMD ["python", "app.py"]
